#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const seed = require("../public/assets/finder-seed.js");
const core = require("../public/assets/finder-core.js");
const articleIndex = require("../public/assets/articles.js");

const SITE_URL = process.env.SITE_URL || "https://wintergator.com";
const BRAND_NAME = "ケモホモ作品ファインダー";
const ROOT_DIR = path.resolve(__dirname, "..");
const PUBLIC_DIR = path.join(ROOT_DIR, "public");
const ARTICLES_DIR = path.join(PUBLIC_DIR, "articles");
const WORKS_DIR = path.join(PUBLIC_DIR, "works");
const COLLECTIONS_DIR = path.join(PUBLIC_DIR, "collections");
const WORK_POSTERS_DIR = path.join(PUBLIC_DIR, "assets", "generated", "work-posters");
const WORK_POSTERS_PATH = "/assets/generated/work-posters";
const DEFAULT_OG_IMAGE = "/assets/og-default.png";
const GENERATED_MARK = "<!-- generated by scripts/build_public_seo_assets.js -->";

const ensureArray = (value) => core.ensureArray(value);

const collapseText = (value) =>
  String(value || "")
    .replace(/\r/g, "")
    .replace(/\n+/g, "\n")
    .replace(/[ \t]+/g, " ")
    .replace(/\u3000/g, " ")
    .trim();

const escapeHtml = (value) =>
  String(value || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");

const escapeJsonForScript = (value) => JSON.stringify(value).replace(/</g, "\\u003c");

const truncate = (value, max = 120) => {
  const text = collapseText(value);
  if (text.length <= max) return text;
  return `${text.slice(0, max - 1).trim()}…`;
};

const absoluteUrl = (value) => {
  if (!value) return SITE_URL;
  if (/^https?:\/\//i.test(value)) return value;
  return new URL(value, SITE_URL).href;
};

const unique = (values) => Array.from(new Set(ensureArray(values).filter(Boolean)));

const ICON_PATHS = {
  work:
    "M4 5h16v14H4V5zm2 2v10h12V7H6zm2 2h8v2H8V9zm0 4h6v2H8v-2z",
  collection:
    "M3 4h8v6H3V4zm10 0h8v6h-8V4zM3 14h8v6H3v-6zm10 0h8v6h-8v-6z",
  tag:
    "M10.5 3H5a2 2 0 0 0-2 2v5.5a2 2 0 0 0 .5858 1.4142l8.5 8.5a2 2 0 0 0 2.8284 0l5.5-5.5a2 2 0 0 0 0-2.8284l-8.5-8.5A2 2 0 0 0 10.5 3zM7 8a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0z",
  compare:
    "M3 4h8v6H3V4zm10 0h8v6h-8V4zM3 14h8v6H3v-6zm10 3h8v-2h-8v2z",
  heart:
    "M12 20.001l-.501-.3088c-.9745-.5626-1.8878-1.2273-2.7655-1.9296-1.1393-.9117-2.4592-2.1279-3.5017-3.5531-1.0375-1.4183-1.8594-3.1249-1.8597-4.9957-.0025-1.2512.3936-2.5894 1.419-3.6149 1.8976-1.8975 4.974-1.8975 6.8716 0l.3347.3347.336-.3347c1.8728-1.8722 4.9989-1.8727 6.8716 0 .9541.954 1.4145 2.2788 1.4191 3.6137 0 3.0657-2.2028 5.7259-4.1367 7.5015-1.2156 1.1161-2.5544 2.1393-3.9813 2.9729L12 20.001z",
  save: "M6 3h12a1 1 0 0 1 1 1v17l-7-4-7 4V4a1 1 0 0 1 1-1z",
};

const BODY_ICON_MAP = {
  "body-normal": {
    src: "/assets/quick-filters/body-normal.png",
    label: "普通体型",
  },
  "body-muscular": {
    src: "/assets/quick-filters/body-muscular.png",
    label: "筋肉・ガチムチ",
  },
  "body-beefy": {
    src: "/assets/quick-filters/body-muscular.png",
    label: "筋肉・ガチムチ",
  },
  "body-fat": {
    src: "/assets/quick-filters/body-fat.png",
    label: "デブ",
  },
};

const renderIconSvg = (kind) => `
  <svg viewBox="0 0 24 24" focusable="false" width="24" height="24" aria-hidden="true">
    <path fill-rule="evenodd" clip-rule="evenodd" d="${escapeHtml(ICON_PATHS[kind] || ICON_PATHS.tag)}"></path>
  </svg>
`;

const renderScriptTags = (scriptUrls = [], { defer = false } = {}) =>
  ensureArray(scriptUrls)
    .filter(Boolean)
    .map((src) => `<script src="${escapeHtml(src)}"${defer ? " defer" : ""}></script>`)
    .join("\n  ");

const isPlaceholderExternalUrl = (value = "") => {
  if (!value) return true;
  try {
    return new URL(value, SITE_URL).hostname === "example.com";
  } catch (error) {
    return true;
  }
};

const getPublicExternalLinks = (work) =>
  ensureArray(work?.externalLinks).filter((link) => link?.url && !isPlaceholderExternalUrl(link.url));

const getVisualTone = (seedValue = "") => {
  const tones = ["sun", "sky", "clay", "mint", "stone"];
  let hash = 0;
  String(seedValue)
    .split("")
    .forEach((char) => {
      hash = (hash * 31 + char.charCodeAt(0)) % 2147483647;
    });
  return tones[Math.abs(hash) % tones.length];
};

const cleanGeneratedChildren = (directoryPath, { preserveNames = [] } = {}) => {
  const preserveNameSet = new Set(ensureArray(preserveNames));
  fs.mkdirSync(directoryPath, { recursive: true });
  fs.readdirSync(directoryPath).forEach((entryName) => {
    if (preserveNameSet.has(entryName)) return;
    fs.rmSync(path.join(directoryPath, entryName), { recursive: true, force: true });
  });
};

const splitTextForPoster = (value, chunkLength = 11, maxLines = 4) => {
  const glyphs = Array.from(String(value || "").trim());
  if (!glyphs.length) return ["作品"];
  const lines = [];
  for (let index = 0; index < glyphs.length && lines.length < maxLines; index += chunkLength) {
    lines.push(glyphs.slice(index, index + chunkLength).join(""));
  }
  if (glyphs.length > chunkLength * maxLines && lines.length) {
    lines[lines.length - 1] = `${lines[lines.length - 1].replace(/.$/, "")}…`;
  }
  return lines;
};

const POSTER_PALETTES = {
  sun: {
    top: "#5c1a16",
    bottom: "#db7a33",
    accent: "#ffd27d",
    chip: "#fff2d1",
  },
  sky: {
    top: "#14335f",
    bottom: "#4a8ed8",
    accent: "#d1ecff",
    chip: "#ebf6ff",
  },
  clay: {
    top: "#4d211d",
    bottom: "#b85b47",
    accent: "#ffd5bf",
    chip: "#fff1e8",
  },
  mint: {
    top: "#0f4035",
    bottom: "#49ab87",
    accent: "#d5fff0",
    chip: "#edfff8",
  },
  stone: {
    top: "#2f3340",
    bottom: "#6f7990",
    accent: "#e4e9f3",
    chip: "#f4f7fc",
  },
};

const getPosterPalette = (work) => POSTER_PALETTES[getVisualTone(work?.id || work?.slug || work?.title)] || POSTER_PALETTES.sky;

const getWorkPosterPath = (work = {}) =>
  `${WORK_POSTERS_PATH}/${encodeURIComponent(work.slug || work.id || "work")}.svg`;

const createWorkPosterSvg = (work) => {
  const palette = getPosterPalette(work);
  const titleLines = splitTextForPoster(work.title, 10, 4);
  const chipLabels = unique([
    ...ensureArray(work.primaryTagObjects).map((tag) => tag?.label).filter(Boolean),
    ...ensureArray(work.highlightPoints),
  ]).slice(0, 3);
  const footerItems = [work.pageCount ? `${work.pageCount}P` : "", work.priceText || "", work.releasedAt || ""].filter(Boolean);
  const kicker = [work.creator || "作品ファインダー", work.format || "作品"].filter(Boolean).join(" / ");
  const subline = collapseText(work.matchSummary || work.publicNote || work.shortDescription || "").slice(0, 72);
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1600" role="img" aria-labelledby="title desc">
  <title id="title">${escapeHtml(work.title || "作品ポスター")}</title>
  <desc id="desc">${escapeHtml(subline || "作品情報の要約ポスター")}</desc>
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${palette.top}" />
      <stop offset="100%" stop-color="${palette.bottom}" />
    </linearGradient>
    <linearGradient id="shine" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="${palette.accent}" stop-opacity="0.28" />
      <stop offset="100%" stop-color="${palette.accent}" stop-opacity="0" />
    </linearGradient>
  </defs>
  <rect width="1200" height="1600" fill="url(#bg)" rx="48" />
  <circle cx="1030" cy="210" r="230" fill="${palette.accent}" fill-opacity="0.18" />
  <circle cx="180" cy="1370" r="280" fill="${palette.accent}" fill-opacity="0.12" />
  <rect x="72" y="72" width="1056" height="1456" rx="36" fill="none" stroke="rgba(255,255,255,0.24)" />
  <rect x="120" y="128" width="252" height="46" rx="23" fill="rgba(255,255,255,0.14)" />
  <text x="148" y="158" fill="#ffffff" font-size="28" font-family="'Hiragino Sans','Yu Gothic',sans-serif" letter-spacing="0.18em">${escapeHtml(kicker.toUpperCase())}</text>
  <rect x="120" y="220" width="960" height="720" rx="42" fill="url(#shine)" />
  ${titleLines
    .map(
      (line, index) => `
  <text
    x="120"
    y="${360 + index * 114}"
    fill="#ffffff"
    font-size="96"
    font-weight="700"
    font-family="'Hiragino Sans','Yu Gothic',sans-serif"
    letter-spacing="0.02em"
  >${escapeHtml(line)}</text>`
    )
    .join("")}
  <text
    x="124"
    y="980"
    fill="rgba(255,255,255,0.9)"
    font-size="34"
    font-family="'Hiragino Sans','Yu Gothic',sans-serif"
  >${escapeHtml(subline || "作品詳細ページから条件と導線を確認できます。")}</text>
  ${chipLabels
    .map(
      (label, index) => `
  <g transform="translate(${120 + index * 300}, 1080)">
    <rect width="256" height="70" rx="35" fill="${palette.chip}" fill-opacity="0.18" stroke="rgba(255,255,255,0.18)" />
    <text
      x="28"
      y="45"
      fill="#ffffff"
      font-size="30"
      font-family="'Hiragino Sans','Yu Gothic',sans-serif"
    >${escapeHtml(label)}</text>
  </g>`
    )
    .join("")}
  <rect x="120" y="1290" width="960" height="162" rx="34" fill="rgba(255,255,255,0.1)" />
  <text
    x="160"
    y="1360"
    fill="#ffffff"
    font-size="52"
    font-weight="700"
    font-family="'Hiragino Sans','Yu Gothic',sans-serif"
  >${escapeHtml(footerItems.join(" ・ ") || "作品詳細ページで確認")}</text>
  <text
    x="160"
    y="1420"
    fill="rgba(255,255,255,0.86)"
    font-size="28"
    font-family="'Hiragino Sans','Yu Gothic',sans-serif"
    letter-spacing="0.08em"
  >WINTERGATOR WORK DETAIL</text>
</svg>
`;
};

const syncGeneratedWorkPosters = (works) => {
  cleanGeneratedChildren(WORK_POSTERS_DIR);
  ensureArray(works).forEach((work) => {
    const filePath = path.join(WORK_POSTERS_DIR, `${work.slug || work.id || "work"}.svg`);
    fs.writeFileSync(filePath, createWorkPosterSvg(work), "utf8");
  });
};

const createFinderUrl = ({
  query = "",
  creatorQuery = "",
  collectionId = "",
  includeTagIds = [],
  excludeTagIds = [],
  matchMode = "and",
} = {}) => {
  const params = new URLSearchParams();
  if (query) params.set("q", query);
  if (creatorQuery) params.set("creator", creatorQuery);
  if (matchMode === "or") params.set("mode", "or");
  unique(includeTagIds).forEach((tagId) => params.append("include", tagId));
  unique(excludeTagIds).forEach((tagId) => params.append("exclude", tagId));
  return params.toString() ? `/?${params.toString()}` : "/";
};

const createBuilderUrl = (params = {}) => {
  const finderUrl = new URL(createFinderUrl(params), SITE_URL);
  return `/builder/${finderUrl.search}`;
};

const createArticlesUrl = ({
  query = "",
  selectedTypes = [],
  selectedTags = [],
  sort = "latest",
  mode = "and",
  page = 1,
} = {}) => {
  const params = new URLSearchParams();
  if (query) params.set("q", query);
  unique(selectedTypes).forEach((value) => params.append("type", value));
  unique(selectedTags).forEach((value) => params.append("tag", value));
  if (sort && sort !== "latest") params.set("sort", sort);
  if (mode === "or") params.set("mode", "or");
  if (page && page > 1) params.set("page", String(page));
  return `/articles/${params.toString() ? `?${params.toString()}` : ""}`;
};

const activeProfile = core.getActiveProfile(seed);
const tagMap = core.getTagMap(seed);
const rawCollectionMap = new Map(ensureArray(seed.collections).map((collection) => [collection.id, collection]));
const decorateWorkLite = (work) => {
  const tagObjects = ensureArray(work.tagIds)
    .map((tagId) => tagMap.get(tagId))
    .filter(Boolean);
  const primaryTagObjects = ensureArray(work.primaryTagIds)
    .map((tagId) => tagMap.get(tagId))
    .filter(Boolean);
  return {
    ...work,
    tagObjects,
    primaryTagObjects: primaryTagObjects.length ? primaryTagObjects : tagObjects.slice(0, 4),
    collectionObjects: ensureArray(work.collectionIds)
      .map((collectionId) => rawCollectionMap.get(collectionId))
      .filter(Boolean),
  };
};
const publishedWorks = ensureArray(seed.works)
  .filter((work) => work.status === "published")
  .map((work) => decorateWorkLite(work));
const workMap = new Map(publishedWorks.map((work) => [work.id, work]));
const workSlugMap = new Map(publishedWorks.map((work) => [work.slug, work]));
const publicCollections = ensureArray(seed.collections)
  .filter((collection) => collection.isPublic !== false)
  .map((collection) => core.decorateCollection(collection, seed));
const collectionMap = new Map(publicCollections.map((collection) => [collection.id, collection]));
const recentArticles = ensureArray(articleIndex)
  .slice()
  .sort((left, right) => Date.parse(right.publishedAt || 0) - Date.parse(left.publishedAt || 0));
const articleTypeCounts = recentArticles.reduce((acc, article) => {
  acc.set(article.type, (acc.get(article.type) || 0) + 1);
  return acc;
}, new Map());

const getWorkBySlug = (slug = "") => workSlugMap.get(slug) || null;

const getRelatedWorksForArticle = (article = {}) =>
  unique(ensureArray(article.relatedWorkSlugs))
    .map((slug) => getWorkBySlug(slug))
    .filter(Boolean);

const getRelatedCollectionsForArticle = (article = {}) =>
  unique(ensureArray(article.relatedCollectionIds))
    .map((collectionId) => collectionMap.get(collectionId))
    .filter(Boolean);

const getRelatedArticlesForWork = (work, limit = 3) => {
  const workSlug = work?.slug;
  const collectionIdSet = new Set(ensureArray(work?.collectionIds));
  const primaryTagIdSet = new Set(ensureArray(work?.primaryTagIds));
  const directMatches = recentArticles.filter((article) =>
    ensureArray(article.relatedWorkSlugs).includes(workSlug)
  );
  if (directMatches.length) return directMatches.slice(0, limit);

  return recentArticles
    .filter((article) => {
      if (ensureArray(article.relatedCollectionIds).some((collectionId) => collectionIdSet.has(collectionId))) {
        return true;
      }
      return ensureArray(article.workTagIds).some((tagId) => primaryTagIdSet.has(tagId));
    })
    .slice(0, limit);
};

const getRelatedArticlesForArticle = (article, limit = 3) => {
  const relatedWorkSlugSet = new Set(ensureArray(article?.relatedWorkSlugs));
  const relatedCollectionIdSet = new Set(ensureArray(article?.relatedCollectionIds));
  const relatedTagIdSet = new Set(ensureArray(article?.workTagIds));
  return recentArticles
    .filter((candidate) => candidate.slug !== article?.slug)
    .map((candidate) => {
      let score = 0;
      ensureArray(candidate.relatedWorkSlugs).forEach((slug) => {
        if (relatedWorkSlugSet.has(slug)) score += 6;
      });
      ensureArray(candidate.relatedCollectionIds).forEach((collectionId) => {
        if (relatedCollectionIdSet.has(collectionId)) score += 4;
      });
      ensureArray(candidate.workTagIds).forEach((tagId) => {
        if (relatedTagIdSet.has(tagId)) score += 2;
      });
      ensureArray(candidate.tags).forEach((tag) => {
        if (ensureArray(article?.tags).includes(tag)) score += 1;
      });
      return { candidate, score };
    })
    .filter((item) => item.score > 0)
    .sort(
      (left, right) =>
        right.score - left.score ||
        Date.parse(right.candidate.publishedAt || 0) - Date.parse(left.candidate.publishedAt || 0)
    )
    .slice(0, limit)
    .map((item) => item.candidate);
};

const resolveProfile = (siteProfileIds = []) => {
  const profileIds = ensureArray(siteProfileIds);
  if (activeProfile && profileIds.includes(activeProfile.id)) return activeProfile;
  return (
    profileIds
      .map((profileId) => core.getProfile(seed, profileId))
      .find(Boolean) ||
    activeProfile
  );
};

const getRealWorkImages = (work) =>
  unique([
    work?.primaryImage?.url,
    work?.hoverImageUrl,
    ...ensureArray(work?.galleryImages).map((item) => item?.url),
    ...ensureArray(work?.galleryImageUrls),
  ]);

const getPrimaryWorkImage = (work) =>
  (work ? getRealWorkImages(work)[0] || getWorkPosterPath(work) : "") || DEFAULT_OG_IMAGE;

const getAllWorkImages = (work) => {
  const realImages = getRealWorkImages(work);
  if (realImages.length) return realImages;
  return [getWorkPosterPath(work)];
};

const getListingWorkImage = (work) => getPrimaryWorkImage(work);

const getArticleImage = (article) => getPrimaryWorkImage(getRelatedWorksForArticle(article)[0]) || DEFAULT_OG_IMAGE;

const getWorkPath = (workOrSlug) => core.getWorkPath(workOrSlug);
const getCollectionPath = (collectionOrSlug) => core.getCollectionPath(collectionOrSlug);

const renderTagChip = ({ label, href = "", className = "tag" }) =>
  href
    ? `<a class="${className}" href="${escapeHtml(href)}">${escapeHtml(label)}</a>`
    : `<span class="${className}">${escapeHtml(label)}</span>`;

const renderFinderMiniLink = ({ label, href, meta = "" }) => `
  <a class="finder-mini-link" href="${escapeHtml(href)}">
    <span class="finder-mini-link__body">
      <strong>${escapeHtml(label)}</strong>
      ${meta ? `<span class="help">${escapeHtml(meta)}</span>` : ""}
    </span>
  </a>
`;

const renderArticleListLink = (article) => `
  <a class="detail-list-link" href="${escapeHtml(article.url)}" data-article-type="${escapeHtml(article.type)}">
    <span class="detail-list-link__thumb">${escapeHtml(article.type)}</span>
    <span class="detail-list-link__body">
      <strong>${escapeHtml(article.title)}</strong>
      <span>${escapeHtml(`${article.type} | ${article.publishedAt}`)}</span>
    </span>
  </a>
`;

const renderArticleCategoryChip = (type, count) => `
  <a class="detail-category-chip" href="${escapeHtml(`/articles/?type=${encodeURIComponent(type)}`)}">
    <strong>${escapeHtml(type)}</strong>
    <span>${count}件</span>
  </a>
`;

const getWorkDisplayTags = (work) =>
  ensureArray(work?.primaryTagObjects).map((tag) => ({
    label: tag.label,
    href: createFinderUrl({ includeTagIds: [tag.id] }),
  }));

const getCharacterTagLabels = (tagIds = []) =>
  unique(
    ensureArray(tagIds)
      .map((tagId) => tagMap.get(tagId)?.label || "")
      .filter(Boolean)
  );

const getCharacterSpeciesLabels = (character = {}) => {
  if (character.speciesLabel) return [character.speciesLabel];
  return getCharacterTagLabels(character.speciesTagIds);
};

const renderCharacterBodyIcons = (character = {}) =>
  unique(ensureArray(character.bodyTypeTagIds))
    .map((tagId) => {
      const icon = BODY_ICON_MAP[tagId];
      if (!icon) return "";
      const label = tagMap.get(tagId)?.label || icon.label;
      return `
        <span class="detail-character-card__bodyIcon" title="${escapeHtml(label)}" aria-label="${escapeHtml(label)}">
          <img src="${escapeHtml(icon.src)}" alt="${escapeHtml(label)}" loading="lazy" decoding="async" />
        </span>
      `;
    })
    .join("");

const renderCharacterCard = (character = {}) => {
  const metaLabels = unique([
    ...getCharacterSpeciesLabels(character),
    ...getCharacterTagLabels(character.ageFeelTagIds),
    character.role || "",
  ]).filter(Boolean);
  const bodyLabels = getCharacterTagLabels(character.bodyTypeTagIds);
  return `
    <article class="detail-character-card">
      <div class="detail-character-card__header">
        <div class="detail-character-card__iconRow">
          ${renderCharacterBodyIcons(character)}
        </div>
        <div class="detail-character-card__copy">
          <strong class="detail-character-card__name">${escapeHtml(character.name || "登場キャラクター")}</strong>
          ${metaLabels.length ? `<p class="detail-character-card__meta">${escapeHtml(metaLabels.join(" / "))}</p>` : ""}
        </div>
      </div>
      ${
        bodyLabels.length
          ? `<div class="detail-character-card__chips">${bodyLabels
              .map((label) => `<span class="detail-character-card__chip">${escapeHtml(label)}</span>`)
              .join("")}</div>`
          : ""
      }
    </article>
  `;
};

const renderWorkCharacters = (work = {}) => {
  const characters = ensureArray(work.characters);
  if (!characters.length) return "";
  return `
    <section class="detail-work-card detail-work-card--characters">
      <p class="detail-section__eyebrow">Characters</p>
      <h2>登場キャラクター</h2>
      <p>種族、年齢感、体型の雰囲気を先に見分けやすいように、主要キャラを一覧でまとめています。</p>
      <div class="detail-character-grid">
        ${characters.map((character) => renderCharacterCard(character)).join("")}
      </div>
    </section>
  `;
};

const renderWorkCard = ({ work, reason = "" }) => {
  const releaseText = work.releasedAt || "公開日未設定";
  const primaryTags = ensureArray(work.primaryTagObjects).slice(0, 4);
  const footnoteItems = [
    work.format || "作品",
    work.pageCount ? `${work.pageCount}P` : "",
    work.priceText || "",
    releaseText,
  ].filter(Boolean);
  return `
    <article class="card work-card work-card--compact" data-tone="${getVisualTone(work.id || work.slug || work.title)}">
      <div class="work-card__visual">
        <a class="work-card__visual-link" href="${escapeHtml(getWorkPath(work))}">
          <span class="work-card__visual-kind">${escapeHtml(work.format || "作品")}</span>
          <strong class="work-card__visual-title">${escapeHtml(work.title)}</strong>
          <div class="work-card__visual-meta">
            <span class="work-card__visual-label">SELECTED</span>
            <strong>${escapeHtml(work.creator || "サンプル作者")}</strong>
          </div>
        </a>
      </div>
      <div class="work-card__body">
        <div class="work-card__header">
          <span class="work-card__creator">${escapeHtml(work.creator || "サンプル作者")}</span>
          <span class="help">${escapeHtml(releaseText)}</span>
        </div>
        <a class="work-card__title" href="${escapeHtml(getWorkPath(work))}">${escapeHtml(work.title)}</a>
        <p class="work-card__summary">${escapeHtml(collapseText(work.shortDescription || work.publicNote || ""))}</p>
        <div class="work-card__meta">
          <strong class="work-card__format">${escapeHtml(work.format || "作品")}</strong>
          <span class="help">${escapeHtml(work.pageCount ? `${work.pageCount}P` : work.highlightPoints?.[0] || "条件要約あり")}</span>
        </div>
        <p class="work-card__reason">${escapeHtml(collapseText(reason || work.matchSummary || work.publicNote || work.shortDescription || ""))}</p>
        <div class="tag-list">
          ${primaryTags
            .map((tag) =>
              renderTagChip({
                label: tag.label,
                href: createFinderUrl({ includeTagIds: [tag.id] }),
              })
            )
            .join("")}
        </div>
        <div class="work-card__footer work-card__footer--solo">
          <a class="btn btn--secondary btn--sm" href="${escapeHtml(getWorkPath(work))}">詳細を見る</a>
        </div>
      </div>
      <p class="help work-card__footnote">${escapeHtml(
        footnoteItems.join(" / ")
      )}</p>
    </article>
  `;
};

const renderWorkGallery = (work) => {
  const mediaUrls = getAllWorkImages(work);
  const realMediaUrls = getRealWorkImages(work);
  if (!mediaUrls.length) {
    return `
      <section class="detail-work-card detail-work-cover detail-work-cover--article">
        <div class="pdp-gallery__hero">
          <div class="pdp-gallery__visual">
            <div class="pdp-gallery__overlay">
              <span class="pdp-gallery__badge">${escapeHtml(work.format || "WORK")}</span>
              <strong>${escapeHtml(work.title)}</strong>
              <p>${escapeHtml(collapseText(work.matchSummary || work.shortDescription || "画像未登録です。"))}</p>
            </div>
          </div>
        </div>
        <div class="pdp-gallery__thumbs">
          ${[work.format || "作品", work.highlightPoints?.[0] || "主要ポイント", work.updatedAt || work.releasedAt || "更新日未設定"]
            .map(
              (label) => `
                <div class="pdp-gallery__thumb pdp-gallery__thumb--placeholder">
                  <strong>${escapeHtml(label)}</strong>
                </div>
              `
            )
            .join("")}
        </div>
        <p class="pdp-gallery__caption">画像未登録の作品です。説明文とタグから合う条件を判断しやすくしています。</p>
      </section>
    `;
  }

  return `
    <section class="detail-work-card detail-work-cover detail-work-cover--article">
      <div class="pdp-gallery__hero">
        <div class="pdp-gallery__visual pdp-gallery__visual--image">
          <img class="pdp-gallery__image" src="${escapeHtml(mediaUrls[0])}" alt="${escapeHtml(`${work.title} のプレビュー画像`)}" decoding="async" fetchpriority="high" />
          <div class="pdp-gallery__overlay">
            <span class="pdp-gallery__badge">${escapeHtml(work.format || "WORK")}</span>
            <strong>${escapeHtml(work.title)}</strong>
            <p>${escapeHtml(collapseText(work.publicNote || work.matchSummary || work.shortDescription || ""))}</p>
          </div>
        </div>
      </div>
      <div class="pdp-gallery__thumbs">
        ${mediaUrls
          .slice(0, 4)
          .map(
            (url, index) => `
              <div class="pdp-gallery__thumb"${index === 0 ? ' data-active="true"' : ""}>
                <img src="${escapeHtml(url)}" alt="${escapeHtml(`${work.title} のサムネイル ${index + 1}`)}" loading="lazy" decoding="async" />
                <span class="pdp-gallery__thumb-label">${index === 0 ? "メイン画像" : `画像 ${index + 1}`}</span>
              </div>
            `
          )
          .join("")}
      </div>
      <p class="pdp-gallery__caption">${
        realMediaUrls.length
          ? `${realMediaUrls.length}枚のメディアを確認できます。`
          : "画像未登録のため、作品情報から生成したポスターを表示しています。"
      }</p>
    </section>
  `;
};

const renderWorkRecommendationCard = (article = null) => {
  const bullets = ensureArray(article?.recommendationBullets);
  if (!bullets.length) return "";
  return `
    <section class="detail-callout">
      <p class="detail-callout__eyebrow">こんな人におすすめ</p>
      <ul class="detail-summary-list">
        ${bullets.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}
      </ul>
    </section>
  `;
};

const renderWorkStoryCard = (paragraphs = []) => {
  const bodyParagraphs = ensureArray(paragraphs).filter(Boolean);
  if (!bodyParagraphs.length) return "";
  return `
    <article class="detail-prose detail-work-card">
      <h2>作品メモ</h2>
      ${bodyParagraphs.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}
    </article>
  `;
};

const renderEditorialFooter = () => `
  <footer class="footer editorial-footer">
    <div class="container editorial-footer__inner">
      <section class="editorial-footer__brand">
        <p class="editorial-footer__eyebrow">作品探索</p>
        <h2 data-site-brand>${escapeHtml(BRAND_NAME)}</h2>
        <p>作品検索を起点に、次に読む作品と次に試す条件をつなぐための土台です。</p>
        <a class="btn btn--primary btn--sm" href="/">作品検索へ</a>
      </section>
      <div class="editorial-footer__column">
        <h3>探す</h3>
        <ul class="editorial-footer__links">
          <li><a href="/">作品検索</a></li>
          <li><a href="/builder/">詳細条件ビルダー</a></li>
        </ul>
      </div>
      <div class="editorial-footer__column">
        <h3>運営</h3>
        <ul class="editorial-footer__links">
          <li><a href="/apply/">掲載申請</a></li>
          <li><a href="/contact/">お問い合わせ</a></li>
          <li><a href="/privacy">プライバシー</a></li>
          <li><a href="/disclaimer">免責事項</a></li>
        </ul>
      </div>
    </div>
    <div class="container editorial-footer__bottom">
      <p class="editorial-footer__legal" data-site-copyright>© ${escapeHtml(BRAND_NAME)}</p>
      <div class="editorial-footer__bottom-links">
        <a href="/">作品検索</a>
        <a href="/builder/">詳細条件</a>
        <a href="/contact/">お問い合わせ</a>
      </div>
    </div>
  </footer>
`;

const renderHead = ({
  title,
  description,
  pathName,
  ogImage = DEFAULT_OG_IMAGE,
  ogImageAlt = "",
  robots = "index,follow,max-image-preview:large",
  themeColor = "#006ce4",
  ogType = "website",
  jsonLd = [],
  scriptUrls = ["/assets/site-config.js", "/assets/finder-seed.js"],
  deferScriptUrls = ["/site.js"],
}) => {
  const absolutePath = absoluteUrl(pathName);
  const absoluteImage = absoluteUrl(ogImage);
  return `
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(title)}</title>
  <meta name="description" content="${escapeHtml(description)}" />
  <link rel="canonical" href="${escapeHtml(absolutePath)}" />
  <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
  <link rel="apple-touch-icon" href="/assets/logo.png" />
  <meta name="robots" content="${escapeHtml(robots)}" />
  <meta name="rating" content="adult" />
  <meta name="author" content="${escapeHtml(BRAND_NAME)}" />
  <meta name="theme-color" content="${escapeHtml(themeColor)}" />
  <meta property="og:site_name" content="${escapeHtml(BRAND_NAME)}" />
  <meta property="og:title" content="${escapeHtml(title)}" />
  <meta property="og:description" content="${escapeHtml(description)}" />
  <meta property="og:type" content="${escapeHtml(ogType)}" />
  <meta property="og:url" content="${escapeHtml(absolutePath)}" />
  <meta property="og:locale" content="ja_JP" />
  <meta property="og:image" content="${escapeHtml(absoluteImage)}" />
  <meta property="og:image:secure_url" content="${escapeHtml(absoluteImage)}" />
  <meta property="og:image:alt" content="${escapeHtml(ogImageAlt || title)}" />
  <meta property="og:image:width" content="1200" />
  <meta property="og:image:height" content="630" />
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content="${escapeHtml(title)}" />
  <meta name="twitter:description" content="${escapeHtml(description)}" />
  <meta name="twitter:image" content="${escapeHtml(absoluteImage)}" />
  <meta name="twitter:image:alt" content="${escapeHtml(ogImageAlt || title)}" />
  <link rel="stylesheet" href="/style.css" />
  ${renderScriptTags(scriptUrls)}
  ${renderScriptTags(deferScriptUrls, { defer: true })}
  ${jsonLd
    .map(
      (payload) =>
        `<script type="application/ld+json">${escapeJsonForScript(payload)}</script>`
    )
    .join("\n  ")}
</head>`.trim();
};

const renderCollectionLinks = (work) =>
  ensureArray(work.collectionIds)
    .map((collectionId) => collectionMap.get(collectionId))
    .filter(Boolean)
    .map((collection) =>
      renderTagChip({
        label: collection.title,
        href: getCollectionPath(collection),
      })
    )
    .join("");

const renderArticleSidebar = () => `
  <section class="detail-widget detail-widget--cta">
    <p class="detail-widget__eyebrow">Finder Hub</p>
    <h3 class="detail-widget__title">次の行き先を決める</h3>
    <p class="detail-widget__text">作品検索に戻るか、詳細条件ビルダーへ進んで条件を詰められます。</p>
    <div class="detail-widget__actions">
      <a class="btn btn--primary" href="/">作品検索へ</a>
      <a class="btn btn--secondary" href="/builder/">詳細条件へ</a>
    </div>
  </section>
`;

const renderPrimaryNav = (currentSection = "") => {
  const navItems = [
    { href: "/", label: "作品を探す", section: "finder" },
    { href: "/apply/", label: "掲載申請", section: "apply" },
    { href: "/contact/", label: "お問い合わせ", section: "contact" },
  ];

  return `
  <nav class="nav">
    <div class="container nav__inner">
      <a class="nav__brand" data-site-brand href="/">${escapeHtml(BRAND_NAME)}</a>
      <div class="nav__links">
        ${navItems
          .map(
            (item) => `
              <a class="nav__link" href="${escapeHtml(item.href)}"${
                item.section === currentSection ? ' aria-current="page"' : ""
              }>${escapeHtml(item.label)}</a>
            `
          )
          .join("")}
      </div>
    </div>
  </nav>
`;
};

const formatDateLabel = (value = "") =>
  /^\d{4}-\d{2}-\d{2}$/.test(value) ? value.replace(/-/g, ".") : value;

const renderHomeShowcaseWorkImage = (work, className, { loading = "lazy", fetchpriority = "" } = {}) => `
  <img
    class="${escapeHtml(className)}"
    src="${escapeHtml(getListingWorkImage(work))}"
    alt="${escapeHtml(`${work?.title || "作品"} のイメージ`)}"
    loading="${escapeHtml(loading)}"
    decoding="async"${fetchpriority ? ` fetchpriority="${escapeHtml(fetchpriority)}"` : ""}
  />
`;

const renderHomeThumb = (work, className = "home-showcase-collage__tile", imageClass = "home-showcase-collage__image") => `
  <span class="${escapeHtml(className)}">
    ${renderHomeShowcaseWorkImage(work, imageClass)}
  </span>
`;

const renderHomeSpotlightBanner = ({ profile, collection, work, relatedWorks = [] }) => `
  <a class="home-showcase-banner home-showcase-banner--spotlight" href="${escapeHtml(
    collection ? getCollectionPath(collection) : "/finder/"
  )}">
    <div class="home-showcase-banner__media">
      ${renderHomeShowcaseWorkImage(work, "home-showcase-banner__image", {
        loading: "eager",
        fetchpriority: "high",
      })}
    </div>
    <span class="home-showcase-banner__scrim"></span>
    <div class="home-showcase-banner__copy">
      <span class="home-showcase-banner__badge">注目導線</span>
      <strong class="home-showcase-banner__title">
        <span class="home-showcase-banner__titleLine">${escapeHtml(profile?.shortName || "ケモホモ")}</span>
        <span class="home-showcase-banner__titleLine">作品ファインダー</span>
      </strong>
      <p class="home-showcase-banner__description">入口作品、特集、条件検索を行き来しながら、次の1冊へ進みやすい導線をトップにまとめています。</p>
      <div class="home-showcase-banner__chipRow">
        ${[
          collection?.title || "入口特集",
          work?.format || "作品紹介",
          ensureArray(work?.highlightPoints)[0] || "導入向け",
        ]
          .filter(Boolean)
          .map((label) => `<span class="home-showcase-banner__chip">${escapeHtml(label)}</span>`)
          .join("")}
      </div>
      <div class="home-showcase-banner__thumbStrip">
        ${relatedWorks.slice(0, 4).map((item) => renderHomeThumb(item, "home-showcase-banner__thumb", "home-showcase-banner__thumbImage")).join("")}
      </div>
    </div>
  </a>
`;

const renderHomeCollageBanner = ({ collection, works = [] }) => `
  <a class="home-showcase-banner home-showcase-banner--collage" href="${escapeHtml(
    collection ? getCollectionPath(collection) : "/collections/"
  )}">
    <div class="home-showcase-banner__intro">
      <span class="home-showcase-banner__badge home-showcase-banner__badge--light">特集</span>
      <div class="home-showcase-banner__yearTitle">
        <strong class="home-showcase-banner__yearNumber">${new Date().getFullYear()}</strong>
        <span class="home-showcase-banner__yearLabel">入口号</span>
      </div>
      <p class="home-showcase-banner__sideDescription">${escapeHtml(
        collection?.title || "複数の入口作品を見比べる特集"
      )}</p>
    </div>
    <div class="home-showcase-collage">
      ${works.slice(0, 6).map((work) => renderHomeThumb(work)).join("")}
    </div>
  </a>
`;

const renderHomePosterBanner = ({ article, work }) => `
  <a class="home-showcase-banner home-showcase-banner--poster" href="${escapeHtml(
    article?.url || getWorkPath(work) || "/finder/"
  )}">
    <span class="home-showcase-banner__badge home-showcase-banner__badge--pink">${escapeHtml(
      article ? "記事" : "作品"
    )}</span>
    <div class="home-showcase-poster__headline">
      <span>${escapeHtml(article ? "記事から" : "作品を")}</span>
      <span>${escapeHtml(article ? "始める" : "探す")}</span>
    </div>
    <p class="home-showcase-poster__note">${escapeHtml(
      article
        ? "まずは作品紹介記事から、体格やシチュの好みを掴むための入口です。"
        : "作品カードから、体格やシチュの好みに近い1冊を探すための入口です。"
    )}</p>
    <div class="home-showcase-poster__footer">
      <p class="home-showcase-poster__footerText">${escapeHtml(
        article?.title || work?.title || "作品一覧から探し方を決める"
      )}</p>
      ${work ? renderHomeThumb(work, "home-showcase-poster__thumb", "home-showcase-collage__image") : ""}
    </div>
  </a>
`;

const renderHomeCompactBanner = ({
  badge = "特集",
  title = "",
  description = "",
  href = "/",
  tone = "light",
}) => `
  <a class="home-showcase-banner home-showcase-banner--compact${
    tone === "dark" ? " home-showcase-banner--compactDark" : ""
  }" href="${escapeHtml(href)}">
    <span class="home-showcase-banner__badge home-showcase-banner__badge--light">${escapeHtml(badge)}</span>
    <div class="home-showcase-compact__title">
      ${String(title)
        .split("\n")
        .map((line) => `<span>${escapeHtml(line)}</span>`)
        .join("")}
    </div>
    <p class="home-showcase-banner__sideDescription">${escapeHtml(description)}</p>
  </a>
`;

const renderHomeProductCard = (work) => `
  <article class="home-showcase-product">
    <a class="home-showcase-product__media" href="${escapeHtml(getWorkPath(work))}">
      ${renderHomeShowcaseWorkImage(work, "home-showcase-product__image")}
      <span class="home-showcase-product__badge">${escapeHtml(work.format || "作品")}</span>
    </a>
    <div class="home-showcase-product__body">
      <p class="home-showcase-product__creator">${escapeHtml(work.creator || "作者未設定")}</p>
      <a class="home-showcase-product__title" href="${escapeHtml(getWorkPath(work))}">${escapeHtml(work.title)}</a>
      <p class="home-showcase-product__meta">${escapeHtml(
        [ensureArray(work.highlightPoints)[0], ensureArray(work.highlightPoints)[1]].filter(Boolean).join(" / ") ||
          collapseText(work.shortDescription || "")
      )}</p>
      <div class="home-showcase-product__footer">
        <strong class="home-showcase-product__price">${escapeHtml(work.priceText || "価格未登録")}</strong>
        <span class="home-showcase-product__detail">${escapeHtml(
          [work.pageCount ? `${work.pageCount}P` : "", work.releasedAt ? `公開 ${work.releasedAt}` : ""]
            .filter(Boolean)
            .join(" / ") || "作品詳細あり"
        )}</span>
      </div>
    </div>
  </article>
`;

const renderHomeCategoryCard = ({ label, meta, href, icon = "tag" }) => `
  <a class="home-showcase-category" href="${escapeHtml(href)}">
    <span class="home-showcase-category__icon">${renderIconSvg(icon)}</span>
    <span class="home-showcase-category__text">
      <strong class="home-showcase-category__title">${escapeHtml(label)}</strong>
      <span class="home-showcase-category__meta">${escapeHtml(meta)}</span>
    </span>
  </a>
`;

const renderHomeTagLink = ({ label, href }) => `
  <a class="home-showcase-tag" href="${escapeHtml(href)}">${escapeHtml(label)}</a>
`;

const renderHomeActionLink = ({ label, href, accent = false }) => `
  <a class="home-showcase-micro__action${accent ? " home-showcase-micro__action--accent" : ""}" href="${escapeHtml(
    href
  )}">${escapeHtml(label)}</a>
`;

const renderArticleCard = (article) => {
  const metaItems = [
    article.type ? `種別 ${article.type}` : "",
    article.publishedAt ? `公開 ${formatDateLabel(article.publishedAt)}` : "",
    article.tags?.[0] ? `タグ ${article.tags[0]}` : "",
  ].filter(Boolean);
  const matchLabels = unique([article.type, ...ensureArray(article.tags).slice(0, 3)]).slice(0, 4);
  const relatedLinks = unique([
    article.type ? createArticlesUrl({ selectedTypes: [article.type] }) : "",
    ...ensureArray(article.tags).slice(0, 2).map((tag) => createArticlesUrl({ selectedTags: [tag] })),
  ])
    .filter(Boolean)
    .map((href, index) => ({
      href,
      label: index === 0 && article.type ? `${article.type}を見る` : ensureArray(article.tags)[index - (article.type ? 1 : 0)] || "関連記事",
    }));

  return `
    <article class="plp-product-card catalog-product-card">
      <a class="catalog-product-card__mediaLink" href="${escapeHtml(article.url)}">
        <div class="catalog-product-card__media">
          <span class="catalog-product-card__badge">${escapeHtml(article.type || "特集記事")}</span>
          <div class="catalog-product-card__mediaVisuals">
            <div class="catalog-product-card__mediaVisual catalog-product-card__mediaVisual--base">
              <img
                class="catalog-product-card__mainImage"
                src="${escapeHtml(getArticleImage(article))}"
                alt="${escapeHtml(`${article.title} のイメージ`)}"
                loading="lazy"
                decoding="async"
              />
            </div>
          </div>
        </div>
      </a>
      <div class="catalog-product-card__body">
        ${matchLabels.length ? `<div class="catalog-product-card__matchTags">${matchLabels.map((label) => `<span class="catalog-product-card__matchTag">${escapeHtml(label)}</span>`).join("")}</div>` : ""}
        <a class="catalog-product-card__title" href="${escapeHtml(article.url)}">${escapeHtml(article.title)}</a>
        <p class="catalog-product-card__subtitle">${escapeHtml(
          [article.type || "特集記事", article.publishedAt ? `公開 ${formatDateLabel(article.publishedAt)}` : ""]
            .filter(Boolean)
            .join("、")
        )}</p>
        <p class="catalog-product-card__detail">${escapeHtml(article.summary || "")}</p>
        <div class="catalog-product-card__metaRow">
          ${metaItems.map((item) => `<span class="catalog-product-card__metaItem">${escapeHtml(item)}</span>`).join("")}
        </div>
        ${
          relatedLinks.length
            ? `
              <p class="catalog-product-card__swatchLabel">近い切り口や次に読む記事</p>
              <div class="catalog-affinity-links">
                ${relatedLinks
                  .map(
                    (item) => `
                      <a class="catalog-affinity-link" href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>
                    `
                  )
                  .join("")}
              </div>
            `
            : ""
        }
      </div>
    </article>
  `;
};

const getArticleCompanionLabel = (article = {}) =>
  article.type === "作品紹介記事" ? "Work Guide" : "Feature";

const toShortChipLabel = (value = "", fallback = "記") => {
  const glyphs = Array.from(String(value || "").trim());
  return glyphs.length ? glyphs.slice(0, 2).join("") : fallback;
};

const renderArticleWorkListLink = (work) => {
  const thumbLabel = toShortChipLabel(
    work?.primaryTagObjects?.[0]?.label || ensureArray(work?.highlightPoints)[0] || work?.format,
    "作"
  );
  const meta = [
    work?.pageCount ? `${work.pageCount}P` : "",
    work?.creator || "",
    collapseText(work?.matchSummary || work?.publicNote || work?.shortDescription || ""),
  ]
    .filter(Boolean)
    .join(" | ");

  return `
    <a class="detail-list-link" href="${escapeHtml(getWorkPath(work))}">
      <span class="detail-list-link__thumb">${escapeHtml(thumbLabel)}</span>
      <span class="detail-list-link__body">
        <strong>${escapeHtml(work.title)}</strong>
        <span>${escapeHtml(meta || "作品詳細へ")}</span>
      </span>
    </a>
  `;
};

const renderArticlePage = (article) => {
  const relatedWorks = getRelatedWorksForArticle(article);
  const relatedCollections = getRelatedCollectionsForArticle(article);
  const relatedArticles = getRelatedArticlesForArticle(article, 3);
  const ogImage = getArticleImage(article);
  const description = truncate(article.summary || article.lead || article.title, 140);
  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "特集記事", item: absoluteUrl("/articles/") },
      { "@type": "ListItem", position: 3, name: article.title, item: absoluteUrl(article.url) },
    ],
  };
  const articleLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: article.title,
    url: absoluteUrl(article.url),
    description,
    datePublished: article.publishedAt || undefined,
    dateModified: article.publishedAt || undefined,
    author: {
      "@type": "Organization",
      name: `${BRAND_NAME} 編集部`,
    },
    image: [absoluteUrl(ogImage)],
    keywords: unique([...ensureArray(article.tags), ...ensureArray(article.keywords)]),
  };
  const articleTagChips = [
    renderTagChip({
      label: article.type || "特集記事",
      href: createArticlesUrl({ selectedTypes: [article.type] }),
    }),
    ...ensureArray(article.tags).map((tag) =>
      renderTagChip({
        label: tag,
        href: createArticlesUrl({ selectedTags: [tag] }),
      })
    ),
    article.publishedAt
      ? renderTagChip({
          label: `公開 ${article.publishedAt}`,
          className: "tag",
        })
      : "",
  ]
    .filter(Boolean)
    .join("");

  return `<!doctype html>
<html lang="ja">
${renderHead({
  title: `${article.title} | ${BRAND_NAME}`,
  description,
  pathName: article.url,
  ogImage,
  ogImageAlt: `${article.title} のイメージ`,
  ogType: "article",
  jsonLd: [breadcrumbLd, articleLd],
  scriptUrls: [
    "/assets/site-config.js",
    "/assets/finder-seed.js",
    "/assets/articles.js",
    "/assets/article-search.js",
  ],
  deferScriptUrls: ["/site.js"],
})}
<body class="editorial-page editorial-page--article">
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav("articles")}
<main id="main">
  <section class="section section--tight">
    <div class="container detail-shell detail-shell--article">
      <div class="detail-primary">
        <p class="detail-breadcrumb"><a href="/">ホーム</a> / <a href="/articles/">特集記事</a> / ${escapeHtml(article.title)}</p>
        <header class="detail-header">
          <div class="detail-badges">
            <span class="detail-badge">${escapeHtml(article.type || "特集記事")}</span>
            <span class="detail-badge detail-badge--muted">${escapeHtml(getArticleCompanionLabel(article))}</span>
          </div>
          <h1 class="detail-title">${escapeHtml(article.title)}</h1>
          <p class="detail-lead">${escapeHtml(collapseText(article.lead || article.summary || ""))}</p>
          <div class="detail-byline">
            <span class="detail-byline__avatar">${escapeHtml(article.type === "作品紹介記事" ? "紹" : "記")}</span>
            <div class="detail-byline__body">
              <strong>${escapeHtml(`${BRAND_NAME} 編集部`)}</strong>
              <span>${escapeHtml(article.publishedAt ? `公開 ${article.publishedAt}` : "公開日未設定")}</span>
            </div>
          </div>
          <div class="detail-tag-row">${articleTagChips}</div>
        </header>

        ${
          ensureArray(article.recommendationBullets).length
            ? `
                <section class="detail-callout">
                  <p class="detail-callout__eyebrow">こんな方におすすめ</p>
                  <ul class="detail-summary-list">
                    ${ensureArray(article.recommendationBullets)
                      .map((item) => `<li>${escapeHtml(item)}</li>`)
                      .join("")}
                  </ul>
                </section>
              `
            : ""
        }

        ${
          relatedWorks.length
            ? `
                <section class="detail-callout">
                  <p class="detail-callout__eyebrow">紹介作品</p>
                  <div class="detail-link-list">
                    ${relatedWorks.map((work) => renderArticleWorkListLink(work)).join("")}
                  </div>
                </section>
              `
            : ""
        }

        ${
          relatedCollections.length
            ? `
                <section class="detail-work-card">
                  <p class="detail-section__eyebrow">Collections</p>
                  <h2>近い入口特集</h2>
                  <p>この作品紹介と近い温度感で横に広げやすい特集をまとめています。</p>
                  <div class="detail-tag-row">
                    ${relatedCollections
                      .map((collection) =>
                        renderTagChip({
                          label: collection.title,
                          href: getCollectionPath(collection),
                        })
                      )
                      .join("")}
                  </div>
                </section>
              `
            : ""
        }

        <article class="detail-prose guide-article-card">
          <h2>作品メモ</h2>
          ${ensureArray(article.bodyParagraphs)
            .map((paragraph) => `<p>${escapeHtml(collapseText(paragraph))}</p>`)
            .join("")}
        </article>

        ${
          article.note
            ? `
                <section class="detail-author-card">
                  <span class="detail-author-card__avatar">注</span>
                  <div class="detail-author-card__body">
                    <strong>補足メモ</strong>
                    <p>${escapeHtml(collapseText(article.note))}</p>
                  </div>
                </section>
              `
            : ""
        }

        <section class="detail-cta-band">
          <p class="detail-section__eyebrow">Next Step</p>
          <h2>次に進む入口</h2>
          <p>紹介作品の詳細へ進むか、記事一覧から近い切り口をたどるかで次の候補を広げられます。</p>
          <div class="detail-widget__actions">
            ${
              relatedWorks[0]
                ? `<a class="btn btn--primary" href="${escapeHtml(getWorkPath(relatedWorks[0]))}">${escapeHtml(
                    `${relatedWorks[0].title} の詳細へ`
                  )}</a>`
                : ""
            }
            ${
              relatedCollections[0]
                ? `<a class="btn btn--secondary" href="${escapeHtml(getCollectionPath(relatedCollections[0]))}">${escapeHtml(
                    `${relatedCollections[0].title} へ`
                  )}</a>`
                : ""
            }
            <a class="btn btn--secondary" href="/articles/">記事一覧へ</a>
          </div>
        </section>

        ${
          relatedArticles.length
            ? `
                <section class="detail-related" id="related-articles">
                  <p class="detail-related__eyebrow">Related</p>
                  <h2>関連記事</h2>
                  <p>近いタグや紹介対象が重なる記事をまとめています。</p>
                  <div class="detail-link-list">
                    ${relatedArticles.map((item) => renderArticleListLink(item)).join("")}
                  </div>
                </section>
              `
            : ""
        }
      </div>

      <aside class="detail-sidebar">
        <section class="detail-widget detail-widget--cta">
          <p class="detail-widget__eyebrow">Article Path</p>
          <h2 class="detail-widget__title">記事から次の1冊へつなぐ</h2>
          <p class="detail-widget__text">作品詳細、特集一覧、作品検索を行き来しながら、近い条件へ広げられます。</p>
          <div class="detail-widget__actions">
            <a class="btn btn--primary" href="/articles/">記事一覧へ</a>
            <a class="btn btn--secondary" href="/finder/">作品検索へ</a>
          </div>
        </section>
        ${renderArticleSidebar({ excludeSlug: article.slug })}
      </aside>
    </div>
  </section>
</main>
${renderEditorialFooter()}
</body>
</html>
`;
};

const renderHomePage = () => {
  const profile = activeProfile;
  const homePageTitle = `${BRAND_NAME} | 条件と除外条件から作品を探す`;
  const homePageDescription =
    "狼、虎、異世界、主従、多種族などの切り口から、ケモホモ作品を条件と作品カード中心で探せる作品ファインダーです。";
  const visibleTags = core.getVisibleTags(seed, profile?.id).slice(0, 24);
  const featuredCollections = publicCollections.filter((collection) =>
    ensureArray(profile?.featuredCollectionIds).includes(collection.id)
  );
  const featuredWorks = publishedWorks.filter((work) =>
    ensureArray(profile?.featuredWorkIds).includes(work.id)
  );
  const recommendedWorks = unique([...featuredWorks.map((work) => work.id), ...publishedWorks.map((work) => work.id)])
    .map((workId) => workMap.get(workId))
    .filter(Boolean)
    .slice(0, 10);
  const introCollection = featuredCollections.find((collection) => collection.id === "start-here") || featuredCollections[0] || publicCollections[0];
  const tfCollection =
    featuredCollections.find((collection) => collection.id === "tf-gateway") ||
    featuredCollections[1] ||
    introCollection;
  const safeCollection =
    featuredCollections.find((collection) => collection.id === "safe-filters") ||
    featuredCollections[2] ||
    introCollection;
  const posterArticle = recentArticles[0];
  const collageWorks = tfCollection
    ? core.getCollectionWorks({
        state: seed,
        profileId: profile?.id,
        collectionId: tfCollection.id,
        sort: "recommended",
      })
    : publishedWorks.slice(0, 6);
  const spotlightWork = featuredWorks[0] || publishedWorks[0];
  const featuredLinkTones = ["rose", "blue", "green", "violet", "yellow"];
  const categoryItems = [
    { label: "狼系", meta: "狼獣人から入りたい", href: createFinderUrl({ includeTagIds: ["species-wolf"] }), icon: "work" },
    {
      label: "虎・ライオン",
      meta: "大型猫寄りを見たい",
      href: createFinderUrl({ includeTagIds: ["species-tiger", "species-lion"], matchMode: "or" }),
      icon: "collection",
    },
    { label: "異世界", meta: "シリーズ物から入る", href: createFinderUrl({ includeTagIds: ["motif-isekai"] }), icon: "compare" },
    { label: "主従", meta: "立場の重さで選ぶ", href: createFinderUrl({ includeTagIds: ["motif-master-servant"] }), icon: "heart" },
    { label: "幼馴染", meta: "距離感の近さから入る", href: createFinderUrl({ includeTagIds: ["motif-childhood-friend"] }), icon: "save" },
    { label: "ぽっちゃり", meta: "体型から入口を決める", href: createFinderUrl({ includeTagIds: ["body-fat"] }), icon: "tag" },
    { label: "入口特集", meta: "固定特集から始める", href: "/collections/", icon: "collection" },
    { label: "詳細条件", meta: "条件を作って絞る", href: "/builder/", icon: "tag" },
  ];
  const websiteLd = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    name: BRAND_NAME,
    url: absoluteUrl("/"),
    description: homePageDescription,
    potentialAction: {
      "@type": "SearchAction",
      target: absoluteUrl("/finder/?q={search_term_string}"),
      "query-input": "required name=search_term_string",
    },
  };
  const featuredCollectionLd = {
    "@context": "https://schema.org",
    "@type": "ItemList",
    name: "注目の入口特集",
    itemListElement: featuredCollections.slice(0, 5).map((collection, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: collection.title,
      url: absoluteUrl(getCollectionPath(collection)),
    })),
  };

  return `<!doctype html>
<html lang="ja">
${renderHead({
  title: homePageTitle,
  description: homePageDescription,
  pathName: "/",
  ogImage: DEFAULT_OG_IMAGE,
  ogImageAlt: `${BRAND_NAME} のトップページ`,
  themeColor: "#ffffff",
  jsonLd: [websiteLd, featuredCollectionLd],
  scriptUrls: [
    "/assets/site-config.js",
    "/assets/finder-seed.js",
    "/assets/finder-core.js",
    "/assets/finder-store.js",
    "/assets/articles.js",
  ],
  deferScriptUrls: ["/site.js", "/assets/catalog-ui.js"],
})}
<body>
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav("home")}
<main id="main" class="main home-showcase-page" data-home-catalog-page>
  <div class="home-showcase-shell">
    <section class="home-showcase-hero">
      <button class="home-showcase-hero__nav home-showcase-hero__nav--prev" type="button" data-home-hero-prev aria-label="前のバナーを表示">
        <span aria-hidden="true">‹</span>
      </button>
      <button class="home-showcase-hero__nav home-showcase-hero__nav--next" type="button" data-home-hero-next aria-label="次のバナーを表示">
        <span aria-hidden="true">›</span>
      </button>
      <div class="home-showcase-hero__rail" data-home-hero-rail>
        <div class="home-showcase-hero__item home-showcase-hero__item--wide" data-hero-slide="0">
          ${renderHomeSpotlightBanner({
            profile,
            collection: introCollection,
            work: spotlightWork,
            relatedWorks: recommendedWorks,
          })}
        </div>
        <div class="home-showcase-hero__item home-showcase-hero__item--medium" data-hero-slide="1">
          ${renderHomeCollageBanner({ collection: tfCollection, works: collageWorks })}
        </div>
        <div class="home-showcase-hero__item home-showcase-hero__item--poster" data-hero-slide="2">
          ${renderHomePosterBanner({ article: posterArticle, work: featuredWorks[1] || recommendedWorks[1] })}
        </div>
        <div class="home-showcase-hero__item home-showcase-hero__item--wide" data-hero-slide="3">
          ${renderHomeCompactBanner({
            badge: "詳細条件",
            title: "条件を\n細かく選ぶ",
            description: "タグ、作者、除外条件をまとめて組み立てる詳細条件ビルダー。",
            href: "/builder/",
            tone: "dark",
          })}
        </div>
        <div class="home-showcase-hero__item home-showcase-hero__item--medium" data-hero-slide="4">
          ${renderHomeCompactBanner({
            badge: "除外条件",
            title: "地雷を\n先に外す",
            description: safeCollection?.title || "強い地雷を避けたい時の入口特集。",
            href: safeCollection ? getCollectionPath(safeCollection) : "/collections/",
          })}
        </div>
      </div>
      <div class="home-showcase-hero__footer">
        <div class="home-showcase-hero__dots" data-home-hero-dots>
          ${Array.from({ length: 5 }, (_, index) => `<button class="home-showcase-hero__dot" type="button" aria-label="バナー ${index + 1} を表示" aria-pressed="${index === 0 ? "true" : "false"}"></button>`).join("")}
        </div>
      </div>
    </section>

    <section class="home-showcase-section">
      <div class="home-showcase-section__head">
        <h2>注目の作品</h2>
      </div>
      <div class="home-showcase-productGrid" data-home-recommended-works>
        ${recommendedWorks.map((work) => renderHomeProductCard(work)).join("")}
      </div>
    </section>

    <section class="home-showcase-section">
      <div class="home-showcase-section__head">
        <h2>探し始める入口</h2>
      </div>
      <div class="home-showcase-categoryGrid" data-home-category-grid>
        ${categoryItems.map((item) => renderHomeCategoryCard(item)).join("")}
      </div>
    </section>

    <section class="home-showcase-section">
      <div class="home-showcase-section__head">
        <h2>人気のタグ</h2>
      </div>
      <div class="home-showcase-tagCloud" data-home-tag-cloud>
        ${visibleTags.map((tag) => renderHomeTagLink({ label: tag.label, href: createFinderUrl({ includeTagIds: [tag.id] }) })).join("")}
      </div>
    </section>

    ${
      recentArticles.length
        ? `
    <section class="card stack">
      <h2 class="h3">最近の特集記事</h2>
      <p class="muted">${escapeHtml(profile?.audienceNote || "まずは入口を迷わせず、その先で深い条件へ落としていく構成です。")}</p>
      <div class="detail-link-list">
        ${recentArticles.slice(0, 4).map((article) => renderArticleListLink(article)).join("")}
      </div>
    </section>
    `
        : ""
    }
  </div>
</main>
${renderEditorialFooter()}
</body>
</html>
`;
};

const renderRootRedirectPage = () => `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="refresh" content="0; url=/finder/" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>作品検索へ移動します | ${escapeHtml(BRAND_NAME)}</title>
  <meta name="robots" content="noindex,follow" />
  <link rel="canonical" href="${escapeHtml(absoluteUrl("/finder/"))}" />
  <script>window.location.replace("/finder/");</script>
</head>
<body>
  ${GENERATED_MARK}
  <p><a href="/finder/">作品検索へ移動します。</a></p>
</body>
</html>
`;

const renderArticlesIndexPage = () => {
  if (!recentArticles.length) {
    const listLd = {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: "特集記事一覧",
      url: absoluteUrl("/articles/"),
      description: "現在公開中の特集記事はありません。",
    };

    return `<!doctype html>
<html lang="ja">
${renderHead({
  title: `特集記事一覧 | ${BRAND_NAME}`,
  description: "現在公開中の特集記事はありません。",
  pathName: "/articles/",
  ogImage: DEFAULT_OG_IMAGE,
  ogImageAlt: "特集記事一覧のOG画像",
  themeColor: "#ffffff",
  jsonLd: [listLd],
  scriptUrls: ["/assets/site-config.js", "/assets/finder-seed.js"],
  deferScriptUrls: ["/site.js"],
})}
<body>
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav("articles")}
<main id="main" class="main">
  <section class="section section--tight">
    <div class="container stack stack--lg">
      <section class="card stack">
        <p class="storefront-eyebrow">Articles</p>
        <h1 class="h2">現在公開中の特集記事はありません</h1>
        <p class="muted">作品は通常の作品カードとして作品検索から探せます。</p>
        <div class="cluster">
          <a class="btn btn--primary" href="/finder/">作品検索へ</a>
          <a class="btn btn--secondary" href="/collections/">特集一覧へ</a>
        </div>
      </section>
    </div>
  </section>
</main>
${renderEditorialFooter()}
</body>
</html>
`;
  }

  const topTags = Array.from(
    recentArticles.reduce((acc, article) => {
      ensureArray(article.tags).forEach((tag) => {
        acc.set(tag, (acc.get(tag) || 0) + 1);
      });
      return acc;
    }, new Map())
  )
    .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0], "ja"))
    .slice(0, 8);
  const listLd = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: "特集記事一覧",
    url: absoluteUrl("/articles/"),
    description: "掲載中の作品紹介記事をまとめた特集記事一覧です。",
    mainEntity: {
      "@type": "ItemList",
      itemListElement: recentArticles.map((article, index) => ({
        "@type": "ListItem",
        position: index + 1,
        name: article.title,
        url: absoluteUrl(article.url),
      })),
    },
  };

  return `<!doctype html>
<html lang="ja">
${renderHead({
  title: `特集記事一覧 | ${BRAND_NAME}`,
  description: "掲載中の作品紹介記事をまとめた特集記事一覧です。",
  pathName: "/articles/",
  ogImage: DEFAULT_OG_IMAGE,
  ogImageAlt: "特集記事一覧のOG画像",
  themeColor: "#ffffff",
  jsonLd: [listLd],
  scriptUrls: [
    "/assets/site-config.js",
    "/assets/finder-seed.js",
    "/assets/finder-core.js",
    "/assets/finder-store.js",
    "/assets/articles.js",
    "/assets/article-search.js",
  ],
  deferScriptUrls: ["/site.js", "/assets/catalog-ui.js"],
})}
<body>
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav("articles")}
<main id="main" class="main catalog-main catalog-search-page" data-articles-catalog-page>
  <div class="catalog-page-shell catalog-search-shell">
    <div class="catalog-search-layout">
      <aside class="catalog-search-sidebar">
        <section class="catalog-search-sidebar__card" data-finder-quick-filters>
          <div class="catalog-quick-filters catalog-quick-filters--articles">
            <div class="catalog-quick-filters__header">
              <div class="catalog-quick-filters__heading">
                <p class="catalog-quick-filters__eyebrow">フィルター</p>
                <h2>記事フィルター</h2>
              </div>
            </div>
            <p class="catalog-quick-filters__summary">キーワード、種別、タグから記事を絞れます。</p>
            <section class="catalog-quick-filter-field">
              <strong class="catalog-quick-filter-field__label">記事タイプ</strong>
              <div class="catalog-quick-filter-chipRow">
                ${Array.from(articleTypeCounts.entries())
                  .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0], "ja"))
                  .map(
                    ([type, count]) => `
                      <a class="catalog-quick-filter-chip" href="${escapeHtml(
                        createArticlesUrl({ selectedTypes: [type] })
                      )}">${escapeHtml(`${type} (${count})`)}</a>
                    `
                  )
                  .join("")}
              </div>
            </section>
            <section class="catalog-quick-filter-field">
              <strong class="catalog-quick-filter-field__label">よく使うタグ</strong>
              <div class="catalog-quick-filter-chipRow">
                ${topTags
                  .map(
                    ([tag, count]) => `
                      <a class="catalog-quick-filter-chip" href="${escapeHtml(
                        createArticlesUrl({ selectedTags: [tag] })
                      )}">${escapeHtml(`${tag} (${count})`)}</a>
                    `
                  )
                  .join("")}
              </div>
            </section>
          </div>
        </section>
        <section class="catalog-search-sidebar__card catalog-search-sidebar__card--compact">
          <label class="catalog-search-sidebar__field">
            <span>並び順</span>
            <select data-finder-sort>
              <option value="latest">新しい順</option>
              <option value="oldest">古い順</option>
              <option value="title">名前順</option>
              <option value="type">種別順</option>
            </select>
          </label>
          <p class="catalog-search-sidebar__help" data-finder-sort-note>公開日が新しい順に並びます。</p>
        </section>
      </aside>
      <section class="catalog-search-results">
        <p aria-live="assertive" class="sr-only" data-finder-a11y-live></p>
        <div class="catalog-search-results__toolbar">
          <div>
            <p class="catalog-search-results__eyebrow">Guide Index</p>
            <h2>記事リスト</h2>
            <p data-finder-status>${escapeHtml(`${recentArticles.length}件 | 新しい順`)}</p>
          </div>
        </div>
        <section class="catalog-search-results__compare" data-finder-compare hidden id="compare-tray"></section>
        <section class="catalog-search-results__empty" data-finder-empty hidden>
          <h2>一致する記事が見つかりません</h2>
          <p>条件を緩めるか、下の入口から近い切り口の記事を探してください。</p>
          <div class="catalog-search-empty-grid">
            <div class="catalog-search-empty-grid__column">
              <h3>記事タイプ</h3>
              <div class="catalog-mini-stack" data-finder-empty-collections></div>
            </div>
            <div class="catalog-search-empty-grid__column">
              <h3>最近の特集</h3>
              <div class="catalog-mini-stack" data-finder-empty-recent></div>
            </div>
            <div class="catalog-search-empty-grid__column">
              <h3>助けが必要なとき</h3>
              <div class="catalog-mini-stack" data-finder-empty-help></div>
            </div>
          </div>
        </section>
        <div class="catalog-product-grid catalog-product-grid--search" id="product-list" data-finder-results>
          ${recentArticles.map((article) => renderArticleCard(article)).join("")}
        </div>
      </section>
    </div>
  </div>
</main>
${renderEditorialFooter()}
</body>
</html>
`;
};

const renderWorkPage = (work) => {
  const profile = resolveProfile(work.siteProfileIds);
  const primaryTags = ensureArray(work.primaryTagObjects);
  const displayTagEntries = getWorkDisplayTags(work);
  const bodyParagraphs = ensureArray(work.bodyParagraphs);
  const leadText = bodyParagraphs[0] || work.shortDescription || work.publicNote || "";
  const storyParagraphs = bodyParagraphs.length > 1 ? bodyParagraphs.slice(1) : ensureArray([work.publicNote]).filter(Boolean);
  const relatedWorks = core.findSimilarWorks({
    state: seed,
    work,
    profileId: profile?.id,
    limit: 3,
  });
  const publicExternalLinks = getPublicExternalLinks(work);
  const description = truncate(leadText || work.publicNote || work.matchSummary, 140);
  const pagePath = getWorkPath(work);
  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "作品検索", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 3, name: work.title, item: absoluteUrl(pagePath) },
    ],
  };
  const creativeWorkLd = {
    "@context": "https://schema.org",
    "@type": "CreativeWork",
    name: work.title,
    url: absoluteUrl(pagePath),
    description,
    author: work.creator
      ? {
          "@type": "Organization",
          name: work.creator,
        }
      : undefined,
    datePublished: work.releasedAt || undefined,
    dateModified: work.updatedAt || work.releasedAt || undefined,
    image: unique([...getAllWorkImages(work), getPrimaryWorkImage(work)]).map((url) => absoluteUrl(url)),
    keywords: unique([
      ...displayTagEntries.map((tag) => tag.label),
      ...ensureArray(work.highlightPoints),
      work.format,
    ]),
  };

  return `<!doctype html>
<html lang="ja">
${renderHead({
  title: `${work.title} | ${BRAND_NAME}`,
  description,
  pathName: pagePath,
  ogImage: getPrimaryWorkImage(work),
  ogImageAlt: `${work.title} のプレビュー画像`,
  ogType: "article",
  jsonLd: [breadcrumbLd, creativeWorkLd],
})}
<body class="editorial-page editorial-page--work">
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav()}
<main id="main">
  <section class="section section--tight">
    <div class="container stack stack--lg">
      <div class="detail-shell detail-shell--work">
        <div class="detail-primary">
          <p class="detail-breadcrumb"><a href="/">ホーム</a> / <a href="/">作品検索</a> / ${escapeHtml(work.title)}</p>
          <header class="detail-header">
            <div class="detail-badges">
              <span class="detail-badge">${escapeHtml(work.format || "作品")}</span>
              <span class="detail-badge detail-badge--muted">${escapeHtml(
                work.releasedAt ? `公開 ${work.releasedAt}` : "公開日未設定"
              )}</span>
            </div>
            <h1 class="detail-title">${escapeHtml(work.title)}</h1>
            <p class="detail-lead">${escapeHtml(collapseText(leadText || work.publicNote || ""))}</p>
            <div class="detail-byline">
              <span class="detail-byline__avatar">${escapeHtml(`${work.creator || work.title}`.trim().slice(0, 1) || "作")}</span>
              <div class="detail-byline__body">
                <strong>${escapeHtml(work.creator || "作者未設定")}</strong>
                <span>${escapeHtml(`最終更新 ${work.updatedAt || work.releasedAt || "未設定"}`)}</span>
              </div>
            </div>
            <div class="detail-tag-row">
              ${displayTagEntries
                .map((tag) =>
                  renderTagChip({
                    label: tag.label,
                    href: tag.href,
                  })
                )
                .join("")}
            </div>
            <div class="detail-fact-grid">
              <div class="detail-fact">
                <span>公開</span>
                <strong>${escapeHtml(work.releasedAt || "未設定")}</strong>
              </div>
              <div class="detail-fact">
                <span>価格</span>
                <strong>${escapeHtml(work.priceText || "未登録")}</strong>
              </div>
              <div class="detail-fact">
                <span>ページ数</span>
                <strong>${escapeHtml(work.pageCount ? `${work.pageCount}P` : "未登録")}</strong>
              </div>
              <div class="detail-fact">
                <span>シリーズ</span>
                <strong>${escapeHtml(work.seriesTitle || "単巻")}</strong>
              </div>
              <div class="detail-fact">
                <span>関連作品</span>
                <strong>${escapeHtml(`${relatedWorks.length}件`)}</strong>
              </div>
            </div>
          </header>
          ${renderWorkCharacters(work)}
          ${renderWorkRecommendationCard({ recommendationBullets: work.recommendationBullets })}
          ${renderWorkGallery(bodyParagraphs.length ? { ...work, publicNote: leadText } : work)}
          ${renderWorkStoryCard(storyParagraphs)}
          <section class="detail-work-card">
            <p class="detail-section__eyebrow">Links</p>
            <h2>外部サイトで作品を確認する</h2>
            ${
              publicExternalLinks.length
                ? `
                    <div class="cluster">
                      ${publicExternalLinks
                        .map(
                          (link) => `
                            <a class="btn btn--primary" href="${escapeHtml(link.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(
                              link.label || "外部リンクを見る"
                            )}</a>
                          `
                        )
                        .join("")}
                    </div>
                  `
                : `<p class="muted">外部リンクは公開準備中です。案内が整い次第、この枠に追加します。</p>`
            }
          </section>
          <section class="detail-related">
            <p class="detail-related__eyebrow">Similar Works</p>
            <h2>近い条件で探しやすい作品</h2>
            <p>タグや雰囲気が近い作品を、次の候補として並べています。</p>
            <div class="storefront-product-grid detail-related-grid--works">
              ${relatedWorks
                .map((item) => {
                  const sharedLabels = ensureArray(item.sharedTagIds)
                    .map((tagId) => tagMap.get(tagId)?.label || tagId)
                    .join(" / ");
                  return renderWorkCard({
                    work: item,
                    reason: sharedLabels ? `近い条件: ${sharedLabels}` : item.matchSummary,
                  });
                })
                .join("")}
            </div>
          </section>
        </div>
        <aside class="detail-sidebar">
          ${renderArticleSidebar()}
        </aside>
      </div>
    </div>
  </section>
</main>
${renderEditorialFooter()}
</body>
</html>
`;
};

const renderCollectionPage = (collection) => {
  const profile = resolveProfile(collection.siteProfileIds);
  const works = core.getCollectionWorks({
    state: seed,
    profileId: profile?.id,
    collectionId: collection.id,
    sort: "recommended",
  });
  const relatedCollections = publicCollections.filter((item) => item.id !== collection.id).slice(0, 4);
  const description = truncate(collection.description || collection.lead, 140);
  const pagePath = getCollectionPath(collection);
  const ogImage = works[0] ? getPrimaryWorkImage(works[0]) : DEFAULT_OG_IMAGE;
  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "ホーム", item: absoluteUrl("/") },
      { "@type": "ListItem", position: 2, name: "特集一覧", item: absoluteUrl("/collections/") },
      { "@type": "ListItem", position: 3, name: collection.title, item: absoluteUrl(pagePath) },
    ],
  };
  const itemListLd = {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    name: collection.title,
    url: absoluteUrl(pagePath),
    description,
    mainEntity: {
      "@type": "ItemList",
      itemListElement: works.map((work, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: absoluteUrl(getWorkPath(work)),
        name: work.title,
      })),
    },
  };

  return `<!doctype html>
<html lang="ja">
${renderHead({
  title: `${collection.title} | ${BRAND_NAME}`,
  description,
  pathName: pagePath,
  ogImage,
  ogImageAlt: `${collection.title} の特集イメージ`,
  jsonLd: [breadcrumbLd, itemListLd],
})}
<body>
${GENERATED_MARK}
<a class="skip-link" href="#main">本文へスキップ</a>
${renderPrimaryNav()}
<main id="main">
  <section class="section section--tight">
    <div class="container stack stack--lg">
      <div class="collection-detail-layout">
        <div class="collection-detail-main stack stack--lg">
          <section class="collection-detail-hero">
            <div class="collection-detail-hero__copy stack">
              <p class="plp-breadcrumb"><a href="/">ホーム</a> / <a href="/collections/">特集</a> / ${escapeHtml(collection.title)}</p>
              <p class="storefront-eyebrow">Collection detail</p>
              <h1 class="h1">${escapeHtml(collection.title)}</h1>
              <p class="lead">${escapeHtml(collapseText(collection.description || ""))}</p>
              <div class="tag-list">
                ${ensureArray(collection.tagObjects)
                  .map((tag) =>
                    renderTagChip({
                      label: tag.label,
                      href: createFinderUrl({ collectionId: collection.id, includeTagIds: [tag.id] }),
                    })
                  )
                  .join("")}
              </div>
            </div>
            <div class="collection-detail-hero__visual storefront-visual storefront-visual--collection">
              <span class="storefront-visual__badge">COLLECTION</span>
              <strong class="storefront-visual__title">Curated path</strong>
            </div>
          </section>
          <div class="collection-detail-grid">
            <section class="card stack">
              <h2 class="h3">この特集の意図</h2>
              <p class="muted">${escapeHtml(collapseText(collection.lead || collection.description || ""))}</p>
            </section>
            <section class="card stack">
              <h2 class="h3">見方のポイント</h2>
              <ul class="list">
                ${ensureArray(collection.introPoints)
                  .map((item) => `<li>${escapeHtml(item)}</li>`)
                  .join("")}
              </ul>
            </section>
          </div>
          <section class="stack">
            <div class="storefront-section__head">
              <div class="stack">
                <p class="storefront-eyebrow">Selected works</p>
                <h2 class="h3">この特集に含まれる作品</h2>
              </div>
            </div>
            <div class="storefront-product-grid">
              ${works
                .map((work) =>
                  renderWorkCard({
                    work,
                    reason: work.matchSummary || work.publicNote,
                  })
                )
                .join("")}
            </div>
          </section>
        </div>
        <aside class="collection-detail-side">
          <div class="card collection-detail-aside stack">
            <p class="storefront-eyebrow">Explore this collection</p>
            <h2 class="h3">この特集で検索する</h2>
            <p class="muted">特集内の候補からさらに条件を足して絞り込みたい場合は、検索ページへ戻れます。</p>
            <a class="btn btn--primary" href="${escapeHtml(createFinderUrl({ collectionId: collection.id }))}">この特集で検索する</a>
            <div class="divider"></div>
            <div class="stack">
              <h3 class="h3">ほかの特集へ</h3>
              <div class="tag-list">
                ${relatedCollections
                  .map((item) =>
                    renderTagChip({
                      label: item.title,
                      href: getCollectionPath(item),
                    })
                  )
                  .join("")}
              </div>
            </div>
            <div class="divider"></div>
            ${
              recentArticles.length
                ? `
            <div class="stack">
              <h3 class="h3">最近公開した記事</h3>
              <div class="detail-link-list">
                ${recentArticles.slice(0, 3).map((article) => renderArticleListLink(article)).join("")}
              </div>
            </div>
            `
                : ""
            }
          </div>
        </aside>
      </div>
    </div>
  </section>
</main>
<footer class="footer">
  <div class="container footer__inner">
    <p class="muted" data-site-copyright>© ${escapeHtml(BRAND_NAME)}</p>
    <div class="footer__links">
      <a href="/">ホーム</a>
      <a href="/finder/">作品検索</a>
      <a href="/collections/">特集一覧</a>
      <a href="/apply/">掲載申請</a>
      <a href="/contact/">お問い合わせ</a>
      <a href="/privacy">プライバシー</a>
      <a href="/disclaimer">免責事項</a>
    </div>
  </div>
</footer>
</body>
</html>
`;
};

const writeFile = (filePath, content) => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  const normalizedContent = `${String(content).replace(/[ \t]+$/gm, "").trimEnd()}\n`;
  fs.writeFileSync(filePath, normalizedContent, "utf8");
};

const buildSitemap = () => {
  const latestPublishedAt =
    publishedWorks
      .map((work) => work.updatedAt || work.releasedAt || "")
      .filter(Boolean)
      .sort()
      .reverse()[0] || "2026-04-02";
  const pages = [
    { loc: absoluteUrl("/"), lastmod: latestPublishedAt, changefreq: "weekly", priority: "1.0" },
    ...publishedWorks.map((work) => ({
      loc: absoluteUrl(getWorkPath(work)),
      lastmod: work.updatedAt || work.releasedAt || latestPublishedAt,
      changefreq: "monthly",
      priority: "0.6",
    })),
  ];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${pages
  .map(
    (page) => `  <url>
    <loc>${escapeHtml(page.loc)}</loc>
    <lastmod>${escapeHtml(page.lastmod)}</lastmod>
    <changefreq>${escapeHtml(page.changefreq)}</changefreq>
    <priority>${escapeHtml(page.priority)}</priority>
  </url>`
  )
  .join("\n")}
</urlset>
`;
  writeFile(path.join(PUBLIC_DIR, "sitemap.xml"), xml);
};

const buildRobots = () => {
  writeFile(
    path.join(PUBLIC_DIR, "robots.txt"),
    `User-agent: *\nAllow: /\nSitemap: ${SITE_URL}/sitemap.xml\n`
  );
};

const buildStaticPages = () => {
  cleanGeneratedChildren(ARTICLES_DIR);
  cleanGeneratedChildren(WORKS_DIR);
  cleanGeneratedChildren(COLLECTIONS_DIR);
  cleanGeneratedChildren(path.join(PUBLIC_DIR, "finder"));
  cleanGeneratedChildren(path.join(PUBLIC_DIR, "collection"));
  syncGeneratedWorkPosters(publishedWorks);
  publishedWorks.forEach((work) => {
    writeFile(path.join(WORKS_DIR, work.slug, "index.html"), renderWorkPage(work));
  });
};

buildStaticPages();
buildSitemap();
buildRobots();

process.stdout.write(
  `generated root search and ${publishedWorks.length} work pages, sitemap, robots\n`
);
